// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

import "github.com/branchkit/plugin-sdk-go"

// TypeParams is the params shape for action "snippets.type (Type snippet)".
type TypeParams struct {
	Text *string `json:"text,omitempty"`
	Name *string `json:"name,omitempty"`
}

// HandleType registers a typed handler for action "snippets.type (Type snippet)".
func HandleType(p *branchkit.Plugin, fn func(TypeParams, *branchkit.OnActionRequest) (any, error)) {
	branchkit.HandleActionTyped(p, "snippets.type", fn)
}
